import { Country, Sticker, Combo } from './types';

// @ts-ignore
import combo490Img from './assets/images/combo_490_figuritas_1781883440459.jpg';
// @ts-ignore
import albumPaniniDoradoImg from './assets/images/album_panini_dorado_10pack_1781885852008.jpg';

export const COUNTRIES: Country[] = [
  { code: 'ARG', name: 'Argentina', flag: '🇦🇷', color: 'from-sky-400 to-white' },
  { code: 'BRA', name: 'Brasil', flag: '🇧🇷', color: 'from-yellow-400 to-green-600' },
  { code: 'FRA', name: 'Francia', flag: '🇫🇷', color: 'from-blue-600 to-red-600' },
  { code: 'ESP', name: 'España', flag: '🇪🇸', color: 'from-red-600 to-yellow-500' },
  { code: 'POR', name: 'Portugal', flag: '🇵🇹', color: 'from-green-600 to-red-600' },
  { code: 'URU', name: 'Uruguay', flag: '🇺🇾', color: 'from-cyan-400 to-white' },
  { code: 'GER', name: 'Alemania', flag: '🇩🇪', color: 'from-black via-red-600 to-yellow-500' },
  { code: 'ENG', name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', color: 'from-white via-red-500 to-red-750' },
];

export const STICKERS: Sticker[] = [
  {
    id: 's-messi',
    name: 'Lionel Messi',
    country: 'ARG',
    code: 'ARG 10',
    price: 3500,
    type: 'legend',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=150&auto=format&fit=crop&q=60',
    stock: 12,
    skills: ['Capitán', 'Balón de Oro', 'Histórico'],
  },
  {
    id: 's-mbappe',
    name: 'Kylian Mbappé',
    country: 'FRA',
    code: 'FRA 10',
    price: 2500,
    type: 'legend',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?w=150&auto=format&fit=crop&q=60',
    stock: 8,
    skills: ['Velocidad', 'Goleador', 'Campeón 2018'],
  },
  {
    id: 's-ronaldo',
    name: 'Cristiano Ronaldo',
    country: 'POR',
    code: 'POR 7',
    price: 2800,
    type: 'legend',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=150&auto=format&fit=crop&q=60',
    stock: 5,
    skills: ['Salto', 'Goleador Histórico', 'Disciplinado'],
  },
  {
    id: 's-neymar',
    name: 'Neymar Jr',
    country: 'BRA',
    code: 'BRA 10',
    price: 1800,
    type: 'shiny',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=150&auto=format&fit=crop&q=60',
    stock: 15,
    skills: ['Regate', 'Creatividad', 'Estilo Jogo Bonito'],
  },
  {
    id: 's-bellingham',
    name: 'Jude Bellingham',
    country: 'ENG',
    code: 'ENG 5',
    price: 1500,
    type: 'shiny',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?w=150&auto=format&fit=crop&q=60',
    stock: 20,
    skills: ['Fuerza', 'Llegada', 'Próxima Generación'],
  },
  {
    id: 's-vinicius',
    name: 'Vinícius Jr',
    country: 'BRA',
    code: 'BRA 11',
    price: 1600,
    type: 'shiny',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=150&auto=format&fit=crop&q=60',
    stock: 14,
    skills: ['Regate', 'Extremo', 'Velocidad Explosiva'],
  },
  {
    id: 's-dibumartinez',
    name: 'Dibu Martínez',
    country: 'ARG',
    code: 'ARG 1',
    price: 1800,
    type: 'shiny',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=150&auto=format&fit=crop&q=60',
    stock: 11,
    skills: ['Atajapenales', 'Personalidad', 'Guante de Oro'],
  },
  {
    id: 's-griezmann',
    name: 'Antoine Griezmann',
    country: 'FRA',
    code: 'FRA 7',
    price: 1200,
    type: 'normal',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=150&auto=format&fit=crop&q=60',
    stock: 25,
    skills: ['Táctica', 'Experiencia', 'Asistencias'],
  },
  {
    id: 's-musiala',
    name: 'Jamal Musiala',
    country: 'GER',
    code: 'GER 14',
    price: 1100,
    type: 'normal',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=150&auto=format&fit=crop&q=60',
    stock: 18,
    skills: ['Conducción', 'Agilidad', 'Joven Maravilla'],
  },
  {
    id: 's-pedri',
    name: 'Pedri',
    country: 'ESP',
    code: 'ESP 26',
    price: 1300,
    type: 'shiny',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?w=150&auto=format&fit=crop&q=60',
    stock: 14,
    skills: ['Visión', 'Pase Preciso', 'Magia'],
  },
  {
    id: 's-valverde',
    name: 'Federico Valverde',
    country: 'URU',
    code: 'URU 15',
    price: 1450,
    type: 'shiny',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=150&auto=format&fit=crop&q=60',
    stock: 16,
    skills: ['Garra Charrúa', 'Gran Remate', 'Todoterreno'],
  },
  {
    id: 's-extra-messi-gold',
    name: 'Leo Messi (Extra Sticker Oro)',
    country: 'ARG',
    code: 'EXT 10G',
    price: 12000,
    type: 'extra',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=150&auto=format&fit=crop&q=60',
    stock: 2,
    skills: ['Ultra Rara', 'Colección de Lujo', 'Edición Limitada'],
  },
];

export const COMBOS: Combo[] = [
  {
    id: 'c-album-dorado-tapa-dura-pack-10',
    name: 'Álbum Oficial Panini Dorado Tapa Dura Copa Mundial 2026 - Pack de 10 (Liquidación)',
    description: 'Edición oficial de lujo con tapas duras metalizadas doradas. Venta exclusiva en pack cerrado de 10 unidades. El precio indicado es por el pack de 10 álbumes dorados tapa dura.',
    price: 320000,
    category: 'albums',
    rating: 4.9,
    image: albumPaniniDoradoImg,
    stock: 45,
    isPopular: true,
  },
  {
    id: 'c-coleccion-completa-sin-repetir',
    name: 'Combo Liquidación: 490 Figuritas Sin Repetir',
    description: 'Espectacular lote en liquidación de 490 figuritas de la Copa Mundial de la FIFA 2026, garantizadas 100% sin repetir. Conseguí la base principal de tu colección de manera rápida, segura y sin duplicados al mejor precio.',
    price: 2000000,
    category: 'packs',
    rating: 5.0,
    image: combo490Img,
    stock: 8,
    isPopular: true,
  },
  {
    id: 'c-pack-10-sin-repetir-liq',
    name: 'Combo Liquidación: 10 Figuritas Sin Repetir',
    description: 'Lote de 10 figuritas de la Copa Mundial de la FIFA 2026, garantizadas 100% sin repetir. Conseguí este sensacional lote a valor proporcional de liquidación para avanzar de forma rápida.',
    price: 40000,
    category: 'packs',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop',
    stock: 250,
    isPopular: true,
  },
  {
    id: 'c-pack-10-sobres',
    name: 'Super Pack de 1000 Sobres Sólidos (Liquidación)',
    description: 'Lote súper masivo de 1000 sobres premium cerrados. ¡Cada sobre viene con 7 figuritas en su interior (7.000 figuritas en total)! Increíble precio promocional de $1.500 por sobre.',
    price: 1500000,
    category: 'packs',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=500&auto=format&fit=crop',
    stock: 12,
    isPopular: true,
  },
  {
    id: 'c-pack-500-sobres',
    name: 'Super Pack de 500 Sobres Sólidos (Liquidación)',
    description: 'Lote masivo de 500 sobres premium cerrados. ¡Cada sobre viene con 7 figuritas en su interior (3.500 figuritas en total)! Increíble precio promocional de $1.500 por sobre.',
    price: 750000,
    category: 'packs',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=500&auto=format&fit=crop',
    stock: 24,
    isPopular: true,
  },
  {
    id: 'c-album-pack-10',
    name: 'Pack de 10 Álbumes Oficiales Panini Copa Mundial 2026 (Liquidación)',
    description: 'Lote cerrado de 10 Álbumes Oficiales Panini de la Copa Mundial de la FIFA 2026. El precio indicado es por el pack cerrado de 10 álbumes (Valor de liquidación especial).',
    price: 300000,
    category: 'albums',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?w=500&auto=format&fit=crop',
    stock: 15,
    isPopular: true,
  },
  {
    id: 'c-lote-100-sin-repetir',
    name: 'Lote de 100 Figuritas Surtidas (Sin Repetir)',
    description: '¡La mejor forma de arrancar tu álbum! Te enviamos 100 figuritas aleatorias garantizadas de no tener ninguna repetida entre sí bajo valor especial de liquidación.',
    price: 400000,
    category: 'combos',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?w=400&auto=format&fit=crop&q=60',
    stock: 0,
  }
];
